from fpdf import FPDF
from datetime import datetime
import io

class CancerReport(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_font('Arial', 'B', 15)
        self.set_text_color(13, 148, 136) # Clinical Teal
        self.cell(0, 10, 'CANCER DETECTIVE - DIAGNOSTIC REPORT', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated on {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def generate_scan_report(patient_info, scan_info):
    pdf = CancerReport()
    pdf.add_page()
    
    # Patient Details Section
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0)
    pdf.cell(0, 10, 'Patient Information', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, f"Name: {patient_info.get('name', 'Anonymous')}", 0, 1)
    pdf.cell(0, 8, f"Age: {patient_info.get('age', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Gender: {patient_info.get('gender', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Contact: {patient_info.get('contact', 'N/A')}", 0, 1)
    pdf.ln(5)
    
    # Scan Details Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Diagnostic Summary', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, f"Scan Type: {scan_info.get('cancer_type', 'N/A')}", 0, 1)
    pdf.cell(0, 8, f"Timestamp: {scan_info.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M'))}", 0, 1)
    
    pdf.ln(5)
    
    # Result Highlight
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Arial', 'B', 14)
    result = scan_info.get('prediction_result', 'N/A')
    confidence = scan_info.get('confidence', 0)
    
    if "Cancerous" in result or "Malignant" in result or "ACA" in result or "SCC" in result:
        pdf.set_text_color(153, 27, 27) # Deep Red
    else:
        pdf.set_text_color(13, 148, 136) # Clinical Teal
        
    pdf.cell(0, 15, f"RESULT: {result}", 1, 1, 'C', fill=True)
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0)
    pdf.cell(0, 10, f"Confidence Level: {confidence*100:.2f}%", 0, 1, 'C')
    
    pdf.ln(10)
    
    # Professional Disclaimer
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(0, 8, 'Clinical Recommendations:', 0, 1)
    pdf.set_font('Arial', '', 9)
    recommendation = "Referral to an oncologist for biopsy and staging is recommended." if "Cancerous" in result or "Malignant" in result else "Periodic screening and monitoring recommended."
    pdf.multi_cell(0, 5, recommendation)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI-assisted tool and should be used only as a support tool for professional medical diagnosis. Final validation by a certified pathologist/oncologist is mandatory.")
    
    # Return as bytes
    return pdf.output()

def generate_report_pdf(patient_info, report_content, prediction):
    pdf = CancerReport()
    pdf.add_page()
    
    # Patient Details
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Patient Information', 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, f"Name: {patient_info.get('name', 'Anonymous')}", 0, 1)
    pdf.ln(5)
    
    # Report Content
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Medical Report Content', 0, 1)
    pdf.set_font('Arial', '', 9)
    pdf.multi_cell(0, 5, report_content)
    
    pdf.ln(10)
    
    # Prediction
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"AI Analysis Status: {prediction}", 0, 1)
    
    return pdf.output()
